name: magento-dev
recipe: lamp
config:
  php: "8.1"
  composer_version: "2.2.18"
  webroot: .
  database: mysql:8.0
services:
  pma:
    type: phpmyadmin
  search:
    type: elasticsearch:7
  appserver:
    build_as_root:
      - apt-get update -y
      - apt install libxslt1-dev -y
      - docker-php-ext-install xsl
      - docker-php-ext-install sockets
